FROM node:21-alpine as build

COPY . /app
WORKDIR /app

RUN yarn install --frozen-lockfile

RUN yarn build




FROM nginx:stable-alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
